' To be uploaded to SRF

Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Melillo").Link("About Us").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Melillo").Link("About Us")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - About").Link("Solutions").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - About").Link("Solutions")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Solutions").Link("Project & Portfolio Management").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Solutions").Link("Project & Portfolio Management")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Project").Link("Solutions").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Project").Link("Solutions")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Solutions").Link("Careers").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Solutions").Link("Careers")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Careers").Link("Contact").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Careers").Link("Contact")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Contact").Link("Executive Team").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Contact").Link("Executive Team")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Executive").Link("Contact").Click @@ hightlight id_;_Browser("Melillo Consulting - Melillo").Page("Melillo Consulting - Executive").Link("Contact")_;_script infofile_;_ZIP::ssf8.xml_;_
